[package]
name = "session-tracker-gui"
version = "0.8.7"
description = "A Tauri App"
authors = ["Cjeera"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "session_tracker_gui_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.7.1", features = [] }
dotenvy = "0.15.7"


[dependencies]
tauri = { version = "2.12.1", features = [] }
tauri-plugin-opener = "^2.7.0"
serde = { version = "^1.0.229", features = ["derive"] }
serde_json = "^1.0.151"
rusqlite = { version = "^0.40.2", features = ["chrono", "bundled", "backup"] }
chrono = { version = "^0.4.45", features = ["serde"] }
sysinfo = "^0.39.6"
csv = "^1.4.0"
thiserror = "^2.0.21"
libsw = "^3.5.0"
fuzzy-matcher = "^0.3.7"
reqwest = { version = "0.13.5", features= ["json", "form", "query"] }
tauri-plugin-dialog = "2.8.1"
tauri-plugin-process = "2.4.0"
dotenvy = "0.15.7"

# Only used during testing
[dev-dependencies]
tokio = { version = "1.53.2", features = ["rt-multi-thread", "macros"] }

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-updater = "2.13.1"
