name: 'publish'

on:
  push:
    branches:
      - release

# Cancels in-progress runs for this workflow if a new push comes in.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-tauri:
    permissions:
      contents: write
    env:
      IGDB_CLIENT_ID: ${{ secrets.IGDB_CLIENT_ID }}
      IGDB_CLIENT_SECRET: ${{ secrets.IGDB_CLIENT_SECRET }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # M1/Arm based Macs
            args: '--target aarch64-apple-darwin'
            rust_target: 'aarch64-apple-darwin'
          - platform: 'macos-latest' # Intel based Macs
            args: '--target x86_64-apple-darwin'
            rust_target: 'x86_64-apple-darwin'
          - platform: 'ubuntu-22.04'
            args: ''
            rust_target: ''
          - platform: 'windows-latest'
            args: ''
            rust_target: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      # Install pnpm 
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.28.2

      # Setup Node and cache pnpm
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'

      # Install Rust
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      # Add Rust targets only if specified in the matrix
      - name: Add Rust target
        if: matrix.rust_target != ''
        run: rustup target add ${{ matrix.rust_target }}

      # Cache Rust build files
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      # Install Ubuntu dependencies
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      # Install frontend dependencies
      - name: install frontend dependencies
        run: pnpm install

      # Run Rust Backend Unit Tests
      - name: Run backend tests
        run: cargo test --manifest-path src-tauri/Cargo.toml

      # Build and Publish with Tauri Action
      - name: Build and Publish Tauri App
        uses: tauri-apps/tauri-action@v0.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: app-v__VERSION__
          releaseName: 'Session Tracker GUI v__VERSION__'
          releaseBody: 'Fix for cover art section.'
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}